# Generated by Django 3.1.1 on 2020-09-21 19:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('samaneh', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='created',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='work',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='work',
            name='estimate',
            field=models.IntegerField(default=99, verbose_name='days'),
        ),
        migrations.AlterField(
            model_name='work',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
